name: Automatic Workflow

on:
  push:
    branches: ["main"]
    
jobs:
  build-and-deploy-project:
    runs-on: ubuntu-latest
    steps:
      - name: Run Bye world
        run: | 
          echo ${{ github.event.push.ref }}
          echo ${{ github.event.push.ref_type }}