name: Manual-Workflow

on:
  repository_dispatch:
    types: [test_result]
# WORKFLOW_ACTION
permissions:
  contents: write
  id-token: write
    
concurrency:
  group: example-group
  cancel-in-progress: true
jobs:
  
  branch-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run hello world
        run: echo "Hello Branch Pipeline!"
      
      - name: create txt file
        run: echo "original workflow"

      - name: added sleep for 2 min
        run: sleep 120s
