name: Manual-Workflow

on:
  workflow_dispatch:
    branches: ["main"]
    inputs:
      clusterName:
        description: 'Cluster Name'
        required: true
        default: something
    
jobs:
  build-and-deploy-project:
    runs-on: ubuntu-latest
    steps:
      
      - name: Print clusterName
        run: echo ${{ inputs.clusterName }}