name: Manual-Workflow
permissions:
  contents: write
  id-token: write
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    branches: ["main"]
    inputs:
      clusterName:
        description: 'Cluster Name'
        required: true
        default: something
    
jobs:
  tag-pipeline:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Run hello worldddd
        run: echo "Hello Tag Branch!"
  
  branch-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Run hello world
        run: echo "Hello Branch Pipeline!"
      
      - name: push to protected branch
        run: |
          touch test.txt
          echo "hello world" > test.txt
          cat test.txt
          git add test.txt
          git commit -m "add test.txt"
          git push