name: Manual-Workflow

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    branches: ["main"]
    inputs:
      clusterName:
        description: 'Cluster Name'
        required: true
        default: something
    
jobs:
  tag-pipeline:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Run hello worldddd
        run: echo "Hello Tag Branch!"
  
  branch-pipeline:
    if: startsWith(github.ref, 'refs/heads/')
    runs-on: ubuntu-latest
    steps:
      - name: Run hello world
        run: echo "Hello Branch Pipeline!"