name: Manual-Workflow

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    branches: ["main"]
    inputs:
      clusterName:
        description: 'Cluster Name'
        required: true
        default: something
    
jobs:
  build-and-deploy-project:
    runs-on: ubuntu-latest
    steps:
      - name: Run hello world
        run: echo "Hello World!"