name: Manual-Workflow

on:
  workflow_dispatch:
    inputs:
      clusterName:
        description: 'Cluster Name'
        required: true
        default: something
  workflow_run:
    branches: ["main"]
    
jobs:
  build-and-deploy-project:
    runs-on: ubuntu-latest
    steps:
      - name: Run hello world
        run: echo "Hello World!"
      
      - name: Print clusterName
        run: echo ${{ inputs.clusterName }}