name: Manual-Workflow

on:
  workflow_dispatch:
    inputs:
      clusterName:
        description: 'Cluster Name'
        required: true
        default: something
    
jobs:
  if: github.ref == 'refs/heads/main'
  build-and-deploy-project:
    runs-on: ubuntu-latest
    steps:
      
      - name: Print clusterName
        run: |
          echo ${{ github.event.push.ref }}
          echo ${{ github.ref }}