name: Manual-Workflow

on:
  push:
    branches: ["main","develop"]
  workflow_dispatch:
    input:
      clusterName:
        description: 'Cluster Name'
        required: true
        default: something
    
jobs:
  build-and-deploy-project:
    runs-on: ubuntu-latest
    steps:
      - name: Run hello world
        run: echo "Hello World!"
      
      - name: Print clusterName
        run: echo {{ inputs.clusterName }}